### PR TITLE
fix

### PR DESCRIPTION
**Pull request by meru-golang**
Added necessary files and fixed some of them.
In addition, I translated it into Japanese.

### CODE REVIEW

**Comment by volty13** [comment]
lol did you just make a duplicate pull request and translated it to Japanese for no reason

**Comment by meru-golang** [comment]
I don't know what you are trying to say, but I translated it because I need to explain it in Japanese when I teach it to people I know!

> lol did you just make a duplicate pull request and translated it to Japanese for no reason

**Comment by volty13** [comment]
> 
> 
> I don't know what you are trying to say, but I translated it because I need to explain it in Japanese when I teach it to people I know!
> 
> > lol did you just make a duplicate pull request and translated it to Japanese for no reason

Ok, I now understand the part with Japanese but next time please don't create pull requests which have done the same thing as you did. It's a waste of time and it's pointless. (unless there's something wrong but I would create a comment for it.

**Comment by meru-golang** [comment]
Okay, okay.
I'll try not to do that next time.
> > 
> 
> > 
> 
> > I don't know what you are trying to say, but I translated it because I need to explain it in Japanese when I teach it to people I know!
> 
> > 
> 
> > > lol did you just make a duplicate pull request and translated it to Japanese for no reason
> 
> 
> 
> Ok, I now understand the part with Japanese but next time please don't create pull requests which have done the same thing as you did. It's a waste of time and it's pointless. (unless there's something wrong but I would create a comment for it.

**Pull request closed without merging**
